name: ANALISIS_CALIDAD_UCV

on:
  push:
    branches:
      - developer
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependencias
        run: poetry install --with dev --no-root

      - name: Instalar pytest-cov y httpx
        run: poetry run pip install pytest-cov httpx

      - name: Crear directorio data
        run: mkdir -p data

      - name: Ejecutar pruebas con cobertura
        run: |
          poetry run pytest \
            --cov=src \
            --cov-report=xml:coverage.xml \
            --cov-report=term-missing \
            -v

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
